<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AppContext" Id="{13bf0f33-380e-0bed-2b6e-cf8581b41dee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AppContext EXTENDS TcoCore.TcoContext
VAR
    _mainStation : MainStation(THIS^);

    {attribute addProperty Name "Versionsnummer Plc"}
    _sVersion : STRING(23);
    //~
    _stProgramVersion : ST_LibVersion;
    //~

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{e0bc1bc7-e259-0efa-2e7d-4ebd073a0fbb}">
      <Declaration><![CDATA[(*~
    <docu>
        <summary>
            Main method of the TcoContext. This is the entry point of any control logic that belongs to this context.
            The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
            This method is abstract, and it must be overridden in derived block.
        </summary>
    </docu>
~*)
METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_mainStation();

//IF (THIS^._startCycleCount MOD 10 = 0) THEN
//    Logger.Push('This is a log entry', eMessageCategory.Trace);
//END_IF;

//IF (THIS^._startCycleCount MOD 125 = 0) THEN
//    Logger.Push('This is a log entry', eMessageCategory.Info);
//END_IF;

//IF (THIS^._startCycleCount MOD 400 = 0) THEN
//    Logger.Push('This is a log entry', eMessageCategory.Warning);
//END_IF;

//IF (THIS^._startCycleCount MOD 2000 = 0) THEN
//    Logger.Push('This is a log entry', eMessageCategory.Error);
//END_IF;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>