<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MainStation" Id="{798bc997-3fcb-062d-368a-8bd830272d4b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MainStation EXTENDS TcoCore.TcoObject
//VAR
//    turckRfidHead : RfidHead(THIS^, T#1MS);
//    sUId          : T_MaxString;
//END_VAR
//VAR
//	    _uid          : BOOL;
//END_VAR

VAR
    //    rfidHead_Test : IVController_Test;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[//TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>