<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TcUnitContext" Id="{ff8fee1d-e13f-0d33-3998-3aaa5d64a3f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcUnitContext EXTENDS TcoCore.TcoContext
VAR
    _mainStation : MainStation(THIS^);

    {attribute addProperty Name "Versionsnummer Plc"}
    _sVersion : STRING(23);
    //~
    _stProgramVersion : ST_LibVersion;
    //~

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{6bdff8bc-6016-0a28-2967-657756b448a9}">
      <Declaration><![CDATA[(*~
    <docu>
        <summary>
            Main method of the TcoContext. This is the entry point of any control logic that belongs to this context.
            The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
            This method is abstract, and it must be overridden in derived block.
        </summary>
    </docu>
~*)
METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
_mainStation();
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>